import { MenuItemDefinition } from '../domain/menu.types';

export const DEFAULT_MENU: MenuItemDefinition[] = [
  {
    code: 'build-your-own-bowl',
    category: 'Bowls',
    name: 'Build Your Own Bowl',
    description: 'Rice bowl with one protein and optional toppings and sauces.',
    basePriceCents: 1290,
    modifierGroups: [
      {
        code: 'protein',
        name: 'Protein',
        required: true,
        minSelections: 1,
        maxSelections: 1,
        options: [
          { code: 'chicken', name: 'Chicken', priceCents: 0 },
          { code: 'tofu', name: 'Tofu', priceCents: 0 },
          { code: 'beef', name: 'Beef', priceCents: 250 },
        ],
      },
      {
        code: 'toppings',
        name: 'Toppings',
        required: false,
        minSelections: 0,
        maxSelections: 3,
        options: [
          { code: 'corn', name: 'Charred Corn', priceCents: 40 },
          { code: 'pickled-onion', name: 'Pickled Onion', priceCents: 30 },
          { code: 'edamame', name: 'Edamame', priceCents: 60 },
          { code: 'avocado', name: 'Avocado', priceCents: 140 },
        ],
      },
      {
        code: 'sauces',
        name: 'Sauces',
        required: false,
        minSelections: 0,
        maxSelections: 2,
        options: [
          { code: 'aji-amarillo', name: 'Aji Amarillo', priceCents: 35 },
          { code: 'sesame-soy', name: 'Sesame Soy', priceCents: 20 },
          { code: 'lime-crema', name: 'Lime Crema', priceCents: 25 },
        ],
      },
    ],
  },
  {
    code: 'street-taco-kit',
    category: 'Tacos',
    name: 'Street Taco Kit',
    description: 'Three tacos with custom protein, toppings and sauces.',
    basePriceCents: 1490,
    modifierGroups: [
      {
        code: 'protein',
        name: 'Protein',
        required: true,
        minSelections: 1,
        maxSelections: 1,
        options: [
          { code: 'pork', name: 'Pork', priceCents: 0 },
          { code: 'chicken', name: 'Chicken', priceCents: 0 },
          { code: 'mushroom', name: 'Mushroom', priceCents: 90 },
        ],
      },
      {
        code: 'toppings',
        name: 'Toppings',
        required: false,
        minSelections: 0,
        maxSelections: 3,
        options: [
          { code: 'cilantro', name: 'Cilantro', priceCents: 10 },
          { code: 'onion', name: 'White Onion', priceCents: 10 },
          { code: 'cheese', name: 'Cotija', priceCents: 60 },
          { code: 'pineapple', name: 'Pineapple', priceCents: 45 },
        ],
      },
      {
        code: 'sauces',
        name: 'Sauces',
        required: false,
        minSelections: 0,
        maxSelections: 2,
        options: [
          { code: 'verde', name: 'Salsa Verde', priceCents: 20 },
          { code: 'roja', name: 'Salsa Roja', priceCents: 20 },
          { code: 'chipotle', name: 'Chipotle Mayo', priceCents: 25 },
        ],
      },
    ],
  },
  {
    code: 'crispy-fries',
    category: 'Sides',
    name: 'Crispy Fries',
    description: 'Salted fries with rosemary.',
    basePriceCents: 490,
    modifierGroups: [],
  },
  {
    code: 'citrus-salad',
    category: 'Sides',
    name: 'Citrus Salad',
    description: 'Greens, orange segments and toasted seeds.',
    basePriceCents: 590,
    modifierGroups: [],
  },
  {
    code: 'sparkling-lime',
    category: 'Drinks',
    name: 'Sparkling Lime',
    description: 'House sparkling lime soda.',
    basePriceCents: 320,
    modifierGroups: [],
  },
  {
    code: 'cold-brew',
    category: 'Drinks',
    name: 'Cold Brew',
    description: 'Small batch cold brew coffee.',
    basePriceCents: 360,
    modifierGroups: [],
  },
  {
    code: 'choco-flan',
    category: 'Dessert',
    name: 'Choco Flan',
    description: 'Chocolate flan with sea salt.',
    basePriceCents: 610,
    modifierGroups: [],
  },
];
